### ISSUE TITLE
AutoArima-IndexError with different input length

### ISSUE THREAD

**Issue by reaperiit** [tgsmith61591/pmdarima#96] opened 2019-01-31 12:21 UTC
#### Description
Given an input array, for auto_arima fitting:

```python
array = np.array([[0.05798965],
       [0.03604914],
       [0.03410612],
       [0.01077787],
       [0.03267638],
       [0.03127893],
       [0.03076586],
       [0.01853175],
       [0.02184347],
       [0.02931863],
       [0.01998124],
       [0.02287116],
       [0.02692508],
       [0.01835118],
       [0.01944345],
       [0.01731182]])
```

with `array.shape = (16,)`

Now when trying to fit the numpy array object with reduced length, 

```
stepwise_model = auto_arima(array[:-2], start_p=1, start_q=1,
                           max_p=3, max_q=3, m=12,
                           start_P=0, seasonal=True,
                           d=1, D=1, trace=True,
                           error_action='ignore',  
                           suppress_warnings=True, 
                           stepwise=True)
```

then get the error.
#### Error

""IndexError ""

```
/anaconda3/lib/python3.6/site-packages/statsmodels/tsa/statespace/sarimax.py in _conditional_sum_squares(endog, k_ar, polynomial_ar, k_ma, polynomial_ma, k_trend, trend_data)
    898 
    899             # Run an ARMA(p,q) model using the just computed residuals as data
--> 900             Y = endog[r:]
    901 
    902             X = np.empty((Y.shape[0], 0))

IndexError: too many indices for array
```

#### Actual Results

But, when I run the below code with complete numpy array

```python
stepwise_model = auto_arima(array, start_p=1, start_q=1,
                           max_p=3, max_q=3, m=12,
                           start_P=0, seasonal=True,
                           d=1, D=1,trace=True,
                           error_action='ignore',  
                           suppress_warnings=True, 
                           stepwise=True) 
```

I get following results:

```
Fit ARIMA: order=(1, 1, 1) seasonal_order=(0, 1, 1, 12); AIC=nan, BIC=nan, Fit time=nan seconds
Fit ARIMA: order=(0, 1, 0) seasonal_order=(0, 1, 0, 12); AIC=-16.894, BIC=-18.696, Fit time=0.101 seconds
Fit ARIMA: order=(1, 1, 0) seasonal_order=(1, 1, 0, 12); AIC=nan, BIC=nan, Fit time=nan seconds
Fit ARIMA: order=(0, 1, 1) seasonal_order=(0, 1, 1, 12); AIC=nan, BIC=nan, Fit time=nan seconds
Fit ARIMA: order=(0, 1, 0) seasonal_order=(1, 1, 0, 12); AIC=nan, BIC=nan, Fit time=nan seconds
Fit ARIMA: order=(0, 1, 0) seasonal_order=(0, 1, 1, 12); AIC=nan, BIC=nan, Fit time=nan seconds
Fit ARIMA: order=(0, 1, 0) seasonal_order=(1, 1, 1, 12); AIC=nan, BIC=nan, Fit time=nan seconds
Fit ARIMA: order=(1, 1, 0) seasonal_order=(0, 1, 0, 12); AIC=nan, BIC=nan, Fit time=nan seconds
Fit ARIMA: order=(0, 1, 1) seasonal_order=(0, 1, 0, 12); AIC=nan, BIC=nan, Fit time=nan seconds
Fit ARIMA: order=(1, 1, 1) seasonal_order=(0, 1, 0, 12); AIC=nan, BIC=nan, Fit time=nan seconds
```

**Comment by tgsmith61591** [comment] 2019-01-31 15:00
At first I thought it might relate to the fact that your endogenous array was 2d, but I can reproduce this. Interestingly, when `D=0`, it seems to function:

```python
>>> auto_arima(array[:-2], start_p=1, start_q=1,
...                            max_p=3, max_q=3, m=12,
...                            start_P=0, seasonal=True,
...                            d=1, D=0, trace=True,
...                            error_action='ignore',
...                            suppress_warnings=True,
...                            stepwise=True)
Fit ARIMA: order=(1, 1, 1) seasonal_order=(0, 0, 1, 12); AIC=nan, BIC=nan, Fit time=nan seconds
Fit ARIMA: order=(0, 1, 0) seasonal_order=(0, 0, 0, 12); AIC=-74.667, BIC=-73.538, Fit time=0.117 seconds
Fit ARIMA: order=(1, 1, 0) seasonal_order=(1, 0, 0, 12); AIC=-72.765, BIC=-70.505, Fit time=0.385 seconds
Fit ARIMA: order=(0, 1, 1) seasonal_order=(0, 0, 1, 12); AIC=nan, BIC=nan, Fit time=nan seconds
Fit ARIMA: order=(0, 1, 0) seasonal_order=(1, 0, 0, 12); AIC=-72.800, BIC=-71.105, Fit time=0.156 seconds
Fit ARIMA: order=(0, 1, 0) seasonal_order=(0, 0, 1, 12); AIC=nan, BIC=nan, Fit time=nan seconds
Fit ARIMA: order=(0, 1, 0) seasonal_order=(1, 0, 1, 12); AIC=nan, BIC=nan, Fit time=nan seconds
Fit ARIMA: order=(1, 1, 0) seasonal_order=(0, 0, 0, 12); AIC=-74.646, BIC=-72.952, Fit time=0.109 seconds
Fit ARIMA: order=(0, 1, 1) seasonal_order=(0, 0, 0, 12); AIC=-76.259, BIC=-74.564, Fit time=0.248 seconds
Fit ARIMA: order=(1, 1, 2) seasonal_order=(0, 0, 0, 12); AIC=nan, BIC=nan, Fit time=nan seconds
Fit ARIMA: order=(0, 1, 1) seasonal_order=(1, 0, 0, 12); AIC=-73.981, BIC=-71.721, Fit time=0.295 seconds
Fit ARIMA: order=(0, 1, 1) seasonal_order=(1, 0, 1, 12); AIC=nan, BIC=nan, Fit time=nan seconds
Fit ARIMA: order=(1, 1, 1) seasonal_order=(0, 0, 0, 12); AIC=-73.942, BIC=-71.682, Fit time=0.161 seconds
Fit ARIMA: order=(0, 1, 2) seasonal_order=(0, 0, 0, 12); AIC=nan, BIC=nan, Fit time=nan seconds
Total fit time: 1.481 seconds
ARIMA(callback=None, disp=0, maxiter=50, method=None, order=(0, 1, 1),
   out_of_sample_size=0, scoring='mse', scoring_args={},
   seasonal_order=(0, 0, 0, 12), solver='lbfgs', start_params=None,
   suppress_warnings=True, transparams=True, trend=None,
   with_intercept=True)
```

We'll dig into this and see what's going on. If it is a product of the seasonal differencing making the array too short, we should be able to detect that and raise a more informative error

**Comment by tgsmith61591** [comment] 2019-03-13 15:58
Adding `help wanted` tag since I'm so swamped between work and other issues I've agreed to look into. Anyone wanting to take on an issue, feel free to start here...

**Comment by tgsmith61591** [comment] 2019-03-27 00:27
Coming back to this, I think it may have to do with `m` being almost as long as the array. Internally, statsmodels is slicing out of bounds. I'm going to close this as not a pmdarima problem, but being a statsmodels problem. When `m` is lower, I can run your code. Also if I double the length of `array`, it works:

```python
array = np.concatenate([array, array])
stepwise_model = auto_arima(array, start_p=1, start_q=1,
                           max_p=3, max_q=3, m=12,
                           start_P=0, seasonal=True,
                           d=1, D=1,trace=True,
                           error_action='ignore',  
                           suppress_warnings=True, 
                           stepwise=True) 
```

I know this is an unsatisfactory answer... but it basically comes down to "`m` is too large for such a small training set." I wish statsmodels would produce a better error message...

**Closed by tgsmith61591** 2019-03-27 00:27 UTC
Labels: :beetle: : bug, help wanted

**Comment by reaperiit** [comment] 2019-03-27 05:26
Thanks!
