### ISSUE TITLE
Long Periods of Seasonality (m=112) takes long time in auto_arima

### ISSUE THREAD

**Issue by RahatKatal** [tgsmith61591/pmdarima#103] opened 2019-03-12 01:51 UTC
#### Description

Hi All,

I am trying to use auto-arima for a long periods of seasonality. However, it seems that it takes a long time to run. In R, we can give fourier function in xreg to convert long seasonality to non-seasonal. 

https://www.rdocumentation.org/packages/forecast/versions/8.5/topics/fourier
https://robjhyndman.com/hyndsight/longseasonality/

is there any equivalent in pmdarima?

Any help will be appreciated.

#### Steps/Code to Reproduce

Here is my statement:

model_fit = auto_arima(user_data.iloc[:, i], error_action='ignore', suppress_warnings=True, m = 112, seasonal= True, D=1, stepwise=True)

**Comment by tgsmith61591** [comment] 2019-03-12 23:37
This is really a duplicate of #102. While there is some work being done for the v1.2.0 release that will dramatically speed up tests of seasonality, the core time waster is actually the internal SARIMAX computation, which is just a slow thing. Can you share R vs Python benchmarks (without Fourier transform) so we can compare apples to apples?

In regards to transforming your data, you could try any of [scipy's many Fourier methods](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.fft.html). I'd be interested to know whether that speeds things up...

**Comment by tgsmith61591** [comment] 2019-03-12 23:38
... but you raise a good point. Maybe specific Fourier functions could be a good addition to the package.

**Comment by tgsmith61591** [comment] 2019-04-07 21:56
Fourier featurizers were added in #121 and will be released in v1.2.0

**Closed by tgsmith61591** 2019-04-07 21:56 UTC
