### ISSUE TITLE
Auto SARIMA not picking up the Periodicity of the seasonality and when i try to give the start and end params, it throws a stationarity error. But for the same dataset if i use auto SARIMA in R i dont get any error.

### ISSUE THREAD

**Issue by bsnithin44** [tgsmith61591/pmdarima#128] opened 2019-04-18 13:58 UTC

**Comment by tgsmith61591** [comment] 2019-04-18 13:58
Exact duplicate of #127.

**Closed by tgsmith61591** 2019-04-18 13:58 UTC
