### ISSUE TITLE
OSError: Could not read saved model state. Does it still exist? when loading a model

### ISSUE THREAD

**Issue by venegas09** [tgsmith61591/pmdarima#107] opened 2019-03-25 15:59 UTC
#### Description
When I run the code below for loading the model to make the prediction, I get the error. The model was trained in AWS Sagemaker and stored in AWS S3. I tried to do the prediction on Sagemaker and locally (downloading the model) but I get the same error all the time.

#### Steps/Code to Reproduce

```def get_model():
    with open('sarima-model.pkl', 'rb') as inp:
        model = pickle.load(inp)
    return model
```

#### Actual Results
File "C:\Python27\lib\site-packages\pyramid\arima\arima.py", line 587, in __setstate__
    'Does it still exist?' % loc)
OSError: Could not read saved model state from /root/.pyramid-arima-cache/2019-03-25_09-54-53.142744-212-8765282940805.pmdpkl. Does it still exist?

#### Versions
   Windows-10-10.0.17763
   ('Python', '2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]')
   ('pmdarima', '0.9.0')
   ('NumPy', '1.16.2')
   ('SciPy', '1.2.1')
   ('Scikit-Learn', '0.20.3')
   ('Statsmodels', '0.9.0')

**Comment by tgsmith61591** [comment] 2019-03-25 17:07
This is a duplicate of #39. What happened in old versions of statsmodels was that model results wrappers were not directly serializable without using their own method, so we had to serialize two artifacts: one `pmdarima` model pickle, and its internal representation in the cache. Obviously when you migrate a model to another filesystem or machine, this breaks things. What I suspect happened is you fit this model in an old version of the package and so it's still looking for the other artifact, which isn't present on your AWS machine.

I'd suggest you retrain in the newest version (v1.1.0) which only serializes ONE pickle artifact and not two.

**Closed by tgsmith61591** 2019-03-25 17:07 UTC
