### ISSUE TITLE
negative dimensions are not allowed

### ISSUE THREAD

**Issue by kkung-kbcloud** [tgsmith61591/pmdarima#207] opened 2019-11-06 07:24 UTC
I am feeding the following series into auto_arima:
```python
Date
2019-10-01 00:00:00+00:00    63.592626
2019-10-02 00:00:00+00:00    63.993472
2019-10-03 00:00:00+00:00    25.442119
2019-10-04 00:00:00+00:00     6.794696
2019-10-05 00:00:00+00:00     6.794694
2019-10-06 00:00:00+00:00     6.794726
2019-10-07 00:00:00+00:00     6.794736
2019-10-08 00:00:00+00:00     6.794735
2019-10-09 00:00:00+00:00     6.794738
2019-10-10 00:00:00+00:00     6.794743
2019-10-11 00:00:00+00:00     6.794745
2019-10-12 00:00:00+00:00     6.794713
2019-10-13 00:00:00+00:00     6.794715
2019-10-14 00:00:00+00:00     6.794716
2019-10-15 00:00:00+00:00     6.794720
2019-10-16 00:00:00+00:00     6.794716
2019-10-17 00:00:00+00:00     6.794720
2019-10-18 00:00:00+00:00     6.794718
2019-10-19 00:00:00+00:00     6.794716
2019-10-20 00:00:00+00:00     6.794715
2019-10-21 00:00:00+00:00     6.794715
2019-10-22 00:00:00+00:00     6.794716
2019-10-23 00:00:00+00:00     6.794720
2019-10-24 00:00:00+00:00     6.794720
2019-10-25 00:00:00+00:00     5.042172
2019-10-26 00:00:00+00:00     6.794715
2019-10-27 00:00:00+00:00     6.794719
2019-10-28 00:00:00+00:00     6.794715
2019-10-29 00:00:00+00:00     6.794715
2019-10-30 00:00:00+00:00     6.794716
2019-10-31 00:00:00+00:00    18.051129
dtype: float64
```

```python
auto_arima(series, start_p=1, start_q=0, start_P=1, start_Q=0, m=PERIOD, seasonal=True, trace=True, error_action='ignore', suppress_warnings=True, stepwise=True)
```

I get the following error message:
> ValueError: negative dimensions are not allowed

**Versions**
Windows-10-10.0.18362-SP0
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
pmdarima 1.3.0
NumPy 1.16.4
SciPy 1.3.1
Scikit-Learn 0.21.2
Statsmodels 0.10.0

**Comment by tgsmith61591** [comment] 2019-11-06 12:53
Duplicate of #191, fixed on master in #193. Will be part of the 1.4.0 release which is coming very soon

**Closed by tgsmith61591** 2019-11-06 12:53 UTC
Labels: :beetle: : bug
